//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Management.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class lmsDiseaseMaster
    {
        public lmsDiseaseMaster()
        {
            this.lmsPatientRegistrations = new HashSet<lmsPatientRegistration>();
            this.lmsOutPatientMasters = new HashSet<lmsOutPatientMaster>();
        }
    
        public int DISEASEID { get; set; }
        public string DISEASENAME { get; set; }
    
        public virtual ICollection<lmsPatientRegistration> lmsPatientRegistrations { get; set; }
        public virtual ICollection<lmsOutPatientMaster> lmsOutPatientMasters { get; set; }
    }
}
