
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsDrugFrequency
{

    public lmsDrugFrequency()
    {

        this.lmsPatientPrescriptions = new HashSet<lmsPatientPrescription>();

    }


    public int FREQUENCYID { get; set; }

    public string FREQUENCY { get; set; }



    public virtual ICollection<lmsPatientPrescription> lmsPatientPrescriptions { get; set; }

}

}
