
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsDeliveryIndication
{

    public int VDIID { get; set; }

    public Nullable<int> OASID { get; set; }

    public Nullable<int> GENDER { get; set; }

    public Nullable<int> WEIGHT { get; set; }

    public Nullable<System.DateTime> TIME { get; set; }

    public Nullable<System.DateTime> DATE { get; set; }

    public string APGAR { get; set; }

    public string BLOODGROUP { get; set; }

    public Nullable<bool> ISFORCEPSDELIVERY { get; set; }



    public virtual lmsObstericAdmissionSheet lmsObstericAdmissionSheet { get; set; }

}

}
