
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsDischargeBill
{

    public int DBILLID { get; set; }

    public Nullable<int> PATIENTID { get; set; }

    public Nullable<System.DateTime> DATEOFDISCHARGE { get; set; }

    public string SERVICEPROVIDED { get; set; }

    public string DISCHARGEADVICE { get; set; }

    public Nullable<int> NOOFDAYSTAY { get; set; }

    public Nullable<double> PHARMACCYCHARGE { get; set; }

    public Nullable<double> BEDORROOMCHARGE { get; set; }

    public Nullable<double> OPERATIONTHEATERCHARGE { get; set; }

    public Nullable<double> OPERATIONCHARGE { get; set; }

    public Nullable<double> SPECILISTDOCTORCHARGE { get; set; }

    public string OPERATINGDOCTOR { get; set; }

    public Nullable<double> ANAESTHESIACHARGE { get; set; }

    public Nullable<double> NURSECHARGE { get; set; }

    public Nullable<double> OTHERSERVICECHARGE { get; set; }

    public Nullable<double> TOTALCHARGE { get; set; }

    public Nullable<double> INSURANCEPAYMENT { get; set; }

    public string INSURANCEPROVIDER { get; set; }

    public Nullable<double> INSURANCEADJUSTMENT { get; set; }

    public Nullable<double> PATIENTPAYMENTS { get; set; }

    public Nullable<double> PATIENTDISCOUNT { get; set; }

    public string COMMENTS { get; set; }

    public Nullable<System.DateTime> CREATEDATE { get; set; }

    public Nullable<int> CREATEUSER { get; set; }

    public Nullable<double> LABOURROOMCHARGE { get; set; }

    public Nullable<double> WARMERPLUSO2CHARGE { get; set; }

    public Nullable<double> PAEDIATRICIANFEE { get; set; }

    public Nullable<double> OXYGENFEE { get; set; }

    public Nullable<double> PHOTOTHERAPYFEE { get; set; }

    public Nullable<double> PAEDIATRICIANRESUSTFEE { get; set; }



    public virtual lmsLoginRegistration lmsLoginRegistration { get; set; }

    public virtual lmsPatientRegistration lmsPatientRegistration { get; set; }

}

}
