//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Management.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class lmsDischargeSummary
    {
        public int SUMMARYID { get; set; }
        public Nullable<int> PATIENTID { get; set; }
        public string PATIENTPROBLEM { get; set; }
        public string PATIENTPREVIOUSHISTORY { get; set; }
        public string SUMMARY { get; set; }
        public string OTHERSUMMARY { get; set; }
        public Nullable<System.DateTime> DISCHARGEDATE { get; set; }
        public Nullable<int> CONSULTEDBY { get; set; }
    
        public virtual lmsLoginRegistration lmsLoginRegistration { get; set; }
        public virtual lmsPatientRegistration lmsPatientRegistration { get; set; }
    }
}
