//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Management.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class lmsGynacDischargeSummary
    {
        public int SUMMARYID { get; set; }
        public Nullable<int> PATIENTID { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public Nullable<System.DateTime> DOD { get; set; }
        public string DIAGNOSIS { get; set; }
        public string PATIENTADMITTEDWITHCO { get; set; }
        public string PASTHISTORY { get; set; }
        public string FAMILYHISTORY { get; set; }
        public string OBSTRICHISTORY { get; set; }
        public string URINEA { get; set; }
        public string URINES { get; set; }
        public string URINED { get; set; }
        public string BlHb { get; set; }
        public string TC { get; set; }
        public string DC { get; set; }
        public string ESR30MT { get; set; }
        public string ESR6OMT { get; set; }
        public string BT { get; set; }
        public string CT { get; set; }
        public string BLPLATELET { get; set; }
        public string BLUREA { get; set; }
        public string BLSUGAR { get; set; }
        public string SRCREATININE { get; set; }
        public string SRCHOLESTEROL { get; set; }
        public string SRT3T4TDH { get; set; }
        public string VDRL { get; set; }
        public string HIV { get; set; }
        public string HBSAG { get; set; }
        public string HCV { get; set; }
        public string CTSCAN { get; set; }
        public string MRISCAN { get; set; }
        public string USG { get; set; }
        public string BIOPSY { get; set; }
        public string SURGECIALPROCEDURE { get; set; }
        public string TREATMENT { get; set; }
        public string POSTOPPERIOD { get; set; }
        public Nullable<System.DateTime> DRESSINGCHANGEDON { get; set; }
        public Nullable<System.DateTime> DISCHARGEDON { get; set; }
        public string CONCLUSIONONDISCHARGE { get; set; }
        public string ADVISE { get; set; }
        public System.DateTime CREATEDATE { get; set; }
    
        public virtual lmsPatientRegistration lmsPatientRegistration { get; set; }
    }
}
