
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsHospitalMaster
{

    public int HOSPITALID { get; set; }

    public string HOSPITALNAME { get; set; }

    public string MANAGEDBY { get; set; }

    public Nullable<bool> ISOCERTIFIED { get; set; }

    public string LOGOPATH { get; set; }

    public string HOSPITALADDRESS { get; set; }

    public Nullable<int> STATEID { get; set; }

    public Nullable<int> CITYID { get; set; }

    public string CONTACT { get; set; }

    public string EMAILID { get; set; }

    public string FAX { get; set; }

    public string QUOTE1 { get; set; }

    public string QUOTE2 { get; set; }

    public System.DateTime CREATEDATE { get; set; }

    public Nullable<int> CREATEDBY { get; set; }



    public virtual lmsCityMaster lmsCityMaster { get; set; }

    public virtual lmsStateMaster lmsStateMaster { get; set; }

    public virtual lmsLoginRegistration lmsLoginRegistration { get; set; }

}

}
