
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsInvestigationReport
{

    public int REPORTID { get; set; }

    public string NAME { get; set; }

    public Nullable<int> AGE { get; set; }

    public Nullable<System.DateTime> REPORTDATE { get; set; }

    public string URINESUGAR { get; set; }

    public string PUSCELL { get; set; }

    public string RBC { get; set; }

    public string EPTHELIALCELL { get; set; }

    public string BLOODHAEMOGLOBIN { get; set; }

    public string GROUPINGRHTYPING { get; set; }

    public string BT { get; set; }

    public string CT { get; set; }

    public string PLATELET { get; set; }

    public string BLOODUREA { get; set; }

    public string SUGAR { get; set; }

    public string SRCREATININE { get; set; }

    public string SRFREET3 { get; set; }

    public string SRFREET4 { get; set; }

    public string TSH { get; set; }

    public string VDRL { get; set; }

    public string HIV { get; set; }

    public string HBSAG { get; set; }

    public string HCV { get; set; }

    public string COMMENTS { get; set; }

    public Nullable<System.DateTime> CREATEDDATE { get; set; }

    public string ALBUMIN { get; set; }

}

}
