
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsLoginRegistration
{

    public lmsLoginRegistration()
    {

        this.lmsDischargeSummaries = new HashSet<lmsDischargeSummary>();

        this.lmsPatientRegistrations = new HashSet<lmsPatientRegistration>();

        this.lmsDischargeBills = new HashSet<lmsDischargeBill>();

        this.lmsSignatureMasters = new HashSet<lmsSignatureMaster>();

        this.lmsHospitalMasters = new HashSet<lmsHospitalMaster>();

    }


    public int LOGINID { get; set; }

    public string FIRSTNAME { get; set; }

    public string MIDDLENAME { get; set; }

    public string LASTNAME { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public Nullable<int> AGE { get; set; }

    public string LOGINADDRESS { get; set; }

    public Nullable<int> STATEID { get; set; }

    public Nullable<int> CITYID { get; set; }

    public Nullable<int> ROLEID { get; set; }

    public string LOGINEMAILID { get; set; }

    public string LOGINPASSWORD { get; set; }

    public string CONTACT { get; set; }

    public Nullable<bool> ISACTIVE { get; set; }

    public Nullable<System.DateTime> CREATEDDATE { get; set; }



    public virtual lmsCityMaster lmsCityMaster { get; set; }

    public virtual ICollection<lmsDischargeSummary> lmsDischargeSummaries { get; set; }

    public virtual lmsRoleMaster lmsRoleMaster { get; set; }

    public virtual lmsStateMaster lmsStateMaster { get; set; }

    public virtual ICollection<lmsPatientRegistration> lmsPatientRegistrations { get; set; }

    public virtual ICollection<lmsDischargeBill> lmsDischargeBills { get; set; }

    public virtual ICollection<lmsSignatureMaster> lmsSignatureMasters { get; set; }

    public virtual ICollection<lmsHospitalMaster> lmsHospitalMasters { get; set; }

}

}
