
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsLabourNote
{

    public int LNID { get; set; }

    public string Name { get; set; }

    public Nullable<int> AGE { get; set; }

    public string IPNO { get; set; }

    public string MODEOFDELIVERY { get; set; }

    public string LABOURNOTES { get; set; }

    public string TREATMENT { get; set; }

    public Nullable<System.DateTime> CREATEDATE { get; set; }

}

}
