
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsMedicalTestFor
{

    public lmsMedicalTestFor()
    {

        this.lmsMedicalTests = new HashSet<lmsMedicalTest>();

    }


    public int TESTFORID { get; set; }

    public string TESTFOR { get; set; }



    public virtual ICollection<lmsMedicalTest> lmsMedicalTests { get; set; }

}

}
