
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsMedicalTestGroup
{

    public lmsMedicalTestGroup()
    {

        this.lmsMedicalTests = new HashSet<lmsMedicalTest>();

    }


    public int GROUPID { get; set; }

    public string GROUPNAME { get; set; }



    public virtual ICollection<lmsMedicalTest> lmsMedicalTests { get; set; }

}

}
