
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsMedicalTest
{

    public lmsMedicalTest()
    {

        this.lmsLaboratoryBillings = new HashSet<lmsLaboratoryBilling>();

        this.lmsLaboratoryBillingDetails = new HashSet<lmsLaboratoryBillingDetail>();

    }


    public int TESTID { get; set; }

    public string TESTNAME { get; set; }

    public Nullable<double> MINAPPROXRANGEBELOW10AGE { get; set; }

    public Nullable<double> MAXAPPROXRANGEBELOW10AGE { get; set; }

    public Nullable<double> MINAPPROXRANGEBELOWADULT { get; set; }

    public Nullable<double> MAXAPPROXRANGEBELOWADULT { get; set; }

    public Nullable<double> SELLIGPRICE { get; set; }

    public string NORMALVALUE { get; set; }

    public Nullable<int> GROUPID { get; set; }

    public Nullable<int> TESTFORID { get; set; }



    public virtual ICollection<lmsLaboratoryBilling> lmsLaboratoryBillings { get; set; }

    public virtual ICollection<lmsLaboratoryBillingDetail> lmsLaboratoryBillingDetails { get; set; }

    public virtual lmsMedicalTestFor lmsMedicalTestFor { get; set; }

    public virtual lmsMedicalTestGroup lmsMedicalTestGroup { get; set; }

}

}
