
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsOutPatientMaster
{

    public lmsOutPatientMaster()
    {

        this.lmsOutPatientDetails = new HashSet<lmsOutPatientDetail>();

    }


    public int OPMASTERID { get; set; }

    public string PATIENTNAME { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public Nullable<int> AGE { get; set; }

    public Nullable<double> WIEGHT { get; set; }

    public Nullable<double> HEIGHT { get; set; }

    public string DIAGNOSISFOR { get; set; }

    public Nullable<System.DateTime> CREATEDATE { get; set; }

    public Nullable<int> GENDER { get; set; }

    public Nullable<int> DISEASEID { get; set; }

    public string CONSULTINGDOCTOR { get; set; }

    public Nullable<double> CONSULTINFEE { get; set; }



    public virtual lmsDiseaseMaster lmsDiseaseMaster { get; set; }

    public virtual ICollection<lmsOutPatientDetail> lmsOutPatientDetails { get; set; }

}

}
