
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsObstericAdmissionSheet
{

    public int OASID { get; set; }

    public string NAME { get; set; }

    public Nullable<int> AGE { get; set; }

    public Nullable<int> GENDER { get; set; }

    public string OCCUPATION { get; set; }

    public string HOSPITALNO { get; set; }

    public string BEDNO { get; set; }

    public string FATHERORHUSBANDNAME { get; set; }

    public Nullable<bool> ISFATHER { get; set; }

    public string OBSCODE { get; set; }

    public string LMP { get; set; }

    public string ADDRESS { get; set; }

    public Nullable<System.DateTime> DODEL { get; set; }

    public Nullable<System.DateTime> EDD { get; set; }

    public string PHONE { get; set; }

    public string MRDEOFDEL { get; set; }

    public Nullable<System.DateTime> DATETIMEOFADMISSION { get; set; }

    public Nullable<System.DateTime> DATETIMEOFDISCHARGE { get; set; }

    public string PATIENTHISTORY { get; set; }

    public string MENARCHE { get; set; }

    public string MENSURALHISTORY { get; set; }

    public string MARITALHISTORY { get; set; }

    public string FAMILYHISTORY { get; set; }

    public string PASTHISTORY { get; set; }

    public string EXAMINATION { get; set; }

    public string TREATMENT { get; set; }

    public Nullable<System.DateTime> CREATEDDATE { get; set; }

}

}
