
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsPatientBooking
{

    public lmsPatientBooking()
    {

        this.lmsPatientPrescriptions = new HashSet<lmsPatientPrescription>();

    }


    public int BOOKINGID { get; set; }

    public Nullable<int> PATIENTID { get; set; }

    public string BOOKINGSTATUS { get; set; }

    public Nullable<System.DateTime> APPOINTMENTDATE { get; set; }

    public Nullable<int> DISEASEID { get; set; }

    public string DOCTORTOCONSULT { get; set; }

    public Nullable<double> CONSULTINGFEE { get; set; }

    public Nullable<System.DateTime> DISCHARGEDATE { get; set; }

    public Nullable<System.DateTime> CREATEDDATE { get; set; }

    public string GENERALINSTRUCTION { get; set; }



    public virtual lmsDiseaseMaster lmsDiseaseMaster { get; set; }

    public virtual ICollection<lmsPatientPrescription> lmsPatientPrescriptions { get; set; }

    public virtual lmsPatientRegistration lmsPatientRegistration { get; set; }

}

}
