
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

    using System;

    public partial class lmsPatientPrescription
    {

        public int PRESCID { get; set; }

        public Nullable<int> BOOKINGID { get; set; }

        public Nullable<int> PATIENTID { get; set; }

        public Nullable<int> DRUGID { get; set; }

        public Nullable<int> MEDICINECOUNT { get; set; }

        public string STRENGTH { get; set; }

        public Nullable<int> DOSAGEID { get; set; }

        public Nullable<int> FREQUENCYID { get; set; }

        public string FREQUENCY { get; set; }

        public string INSTRUCTIONS { get; set; }



        public virtual lmsDrugDosage lmsDrugDosage { get; set; }

        public virtual lmsDrugFrequency lmsDrugFrequency { get; set; }

        public virtual lmsDrug lmsDrug { get; set; }

        public virtual lmsPatientBooking lmsPatientBooking { get; set; }

        public virtual lmsPatientRegistration lmsPatientRegistration { get; set; }

    }

}
