
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    
public partial class lmsPatientReportStore
{

    public int REPORTID { get; set; }

    public Nullable<int> PATIENTID { get; set; }

    public string CONTACT { get; set; }

    public string PATIENTNAME { get; set; }

    public string REPORTDETAIL { get; set; }

    public Nullable<System.DateTime> CREATEDDATE { get; set; }



    public virtual lmsPatientRegistration lmsPatientRegistration { get; set; }

}

}
