
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsPatientRegistration
{

    public lmsPatientRegistration()
    {

        this.lmsDischargeSummaries = new HashSet<lmsDischargeSummary>();

        this.lmsInPatientBillings = new HashSet<lmsInPatientBilling>();

        this.lmsScanReportMasters = new HashSet<lmsScanReportMaster>();

        this.lmsDischargeBills = new HashSet<lmsDischargeBill>();

        this.lmsPatientDischargeSummaries = new HashSet<lmsPatientDischargeSummary>();

        this.lmsPatientTemplates = new HashSet<lmsPatientTemplate>();

        this.lmsGeneralDischargeSummaries = new HashSet<lmsGeneralDischargeSummary>();

        this.lmsGynacDischargeSummaries = new HashSet<lmsGynacDischargeSummary>();

        this.lmsPatientBookings = new HashSet<lmsPatientBooking>();

        this.lmsPatientBookings1 = new HashSet<lmsPatientBooking>();

        this.lmsPatientPrescriptions = new HashSet<lmsPatientPrescription>();

    }


    public int PATIENTID { get; set; }

    public string PATIENTNAME { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public Nullable<int> AGE { get; set; }

    public string PATIENTADDRESS { get; set; }

    public string CONTACT { get; set; }

    public string PATIENTEMAILID { get; set; }

    public string PATIENTTYPE { get; set; }

    public Nullable<System.DateTime> CREATEDDATE { get; set; }

    public string GENDER { get; set; }

    public string QrCodeContent { get; set; }

    public string QrCodeBase64 { get; set; }



    public virtual ICollection<lmsDischargeSummary> lmsDischargeSummaries { get; set; }

    public virtual ICollection<lmsInPatientBilling> lmsInPatientBillings { get; set; }

    public virtual ICollection<lmsScanReportMaster> lmsScanReportMasters { get; set; }

    public virtual ICollection<lmsDischargeBill> lmsDischargeBills { get; set; }

    public virtual ICollection<lmsPatientDischargeSummary> lmsPatientDischargeSummaries { get; set; }

    public virtual ICollection<lmsPatientTemplate> lmsPatientTemplates { get; set; }

    public virtual ICollection<lmsGeneralDischargeSummary> lmsGeneralDischargeSummaries { get; set; }

    public virtual ICollection<lmsGynacDischargeSummary> lmsGynacDischargeSummaries { get; set; }

    public virtual ICollection<lmsPatientBooking> lmsPatientBookings { get; set; }

    public virtual ICollection<lmsPatientBooking> lmsPatientBookings1 { get; set; }

    public virtual ICollection<lmsPatientPrescription> lmsPatientPrescriptions { get; set; }

}

}
