//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Management.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class lmsRoleMaster
    {
        public lmsRoleMaster()
        {
            this.lmsLoginRegistrations = new HashSet<lmsLoginRegistration>();
        }
    
        public int ROLEID { get; set; }
        public string ROLENAME { get; set; }
    
        public virtual ICollection<lmsLoginRegistration> lmsLoginRegistrations { get; set; }
    }
}
