
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsSurgeryNote
{

    public int SNID { get; set; }

    public string NAME { get; set; }

    public Nullable<int> AGE { get; set; }

    public string IPNO { get; set; }

    public string NAMEOFSURGERY { get; set; }

    public string INDICATION { get; set; }

    public string DB { get; set; }

    public string DR { get; set; }

    public string ANAES { get; set; }

    public string AB { get; set; }

    public string SN { get; set; }

    public string SNPROCEDURE { get; set; }

    public string TREATMENT { get; set; }

    public Nullable<System.DateTime> CREDATEDDATE { get; set; }

}

}
