//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Management.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class lmsSignatureMaster
    {
        public lmsSignatureMaster()
        {
            this.lmsTemplateMasters = new HashSet<lmsTemplateMaster>();
        }
    
        public int SIGNATUREID { get; set; }
        public Nullable<int> SIGNATUREFOR { get; set; }
        public string SIGNATUREPATH { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
    
        public virtual lmsLoginRegistration lmsLoginRegistration { get; set; }
        public virtual ICollection<lmsTemplateMaster> lmsTemplateMasters { get; set; }
    }
}
