//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Management.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class lmsStateMaster
    {
        public lmsStateMaster()
        {
            this.lmsHospitalMasters = new HashSet<lmsHospitalMaster>();
            this.lmsLoginRegistrations = new HashSet<lmsLoginRegistration>();
        }
    
        public int STATEID { get; set; }
        public string STATENAME { get; set; }
        public Nullable<int> CITYID { get; set; }
    
        public virtual lmsCityMaster lmsCityMaster { get; set; }
        public virtual ICollection<lmsHospitalMaster> lmsHospitalMasters { get; set; }
        public virtual ICollection<lmsLoginRegistration> lmsLoginRegistrations { get; set; }
    }
}
