
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsScanReportMaster
{

    public lmsScanReportMaster()
    {

        this.lmsScanReportDetails = new HashSet<lmsScanReportDetail>();

    }


    public int SCANREPORTID { get; set; }

    public Nullable<int> SCANID { get; set; }

    public Nullable<int> PATIENTID { get; set; }

    public string REFEREDBY { get; set; }

    public Nullable<double> BILLAMOUNT { get; set; }

    public Nullable<System.DateTime> BILLDATE { get; set; }

    public Nullable<System.DateTime> REPORTDATE { get; set; }



    public virtual lmsPatientRegistration lmsPatientRegistration { get; set; }

    public virtual ICollection<lmsScanReportDetail> lmsScanReportDetails { get; set; }

    public virtual lmsScan lmsScan { get; set; }

}

}
