//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Management.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class lmsScanReportDetail
    {
        public int SCANREPORTDETAILSID { get; set; }
        public Nullable<int> SCANREPORTID { get; set; }
        public string REPORTSUMMARY { get; set; }
        public string REPORTDESCRIPTION { get; set; }
    
        public virtual lmsScanReportMaster lmsScanReportMaster { get; set; }
    }
}
