
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsUltrSonogramReportTwo
{

    public int REPORTID { get; set; }

    public string NAME { get; set; }

    public Nullable<int> AGE { get; set; }

    public string IPNO { get; set; }

    public string OBSTERICCODE { get; set; }

    public string EDD { get; set; }

    public string LMP { get; set; }

    public string BPD { get; set; }

    public string HC { get; set; }

    public string FL { get; set; }

    public string AC { get; set; }

    public string AFI { get; set; }

    public string PLACENTA { get; set; }

    public string PWEIGHT { get; set; }

    public string GA { get; set; }

    public string PRESENTATION { get; set; }

    public string IMPRESSION { get; set; }

    public string COMMENTES { get; set; }

    public Nullable<System.DateTime> CREATEDDATE { get; set; }

}

}
