
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsUltrSonogramReportOne
{

    public int REPORTID { get; set; }

    public string NAME { get; set; }

    public Nullable<int> AGE { get; set; }

    public string LMP { get; set; }

    public string EDD { get; set; }

    public string CRL { get; set; }

    public string UTERUS { get; set; }

    public string GS { get; set; }

    public string CERVIX { get; set; }

    public string PLACENTA { get; set; }

    public string RO { get; set; }

    public string LO { get; set; }

    public string YOLKSAC { get; set; }

    public string FTALHEART { get; set; }

    public string GA { get; set; }

    public string IMPRESSION { get; set; }

    public Nullable<System.DateTime> CREATEDDATE { get; set; }

    public string COMMENTS { get; set; }

    public string POA { get; set; }

}

}
