
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsVaccumDeliveryNote
{

    public int VDNID { get; set; }

    public Nullable<int> OCSID { get; set; }

    public Nullable<System.DateTime> DATE { get; set; }

    public string TREATMENT { get; set; }



    public virtual lmsOtherCaseSheet lmsOtherCaseSheet { get; set; }

}

}
