
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab.Management.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class lmsWard
{

    public int WARDID { get; set; }

    public string WARDNAME { get; set; }

    public Nullable<int> BEDID { get; set; }

    public Nullable<bool> ISACTIVE { get; set; }

    public double ChargePerDay { get; set; }



    public virtual lmsBed lmsBed { get; set; }

}

}
