
namespace Lab.Management.Common
{
    public enum ConfigKey
    {
        LMS
        ,
        SmtpHost
            ,
        SmtpUserName
            ,
        SmtpPassword
            ,
        SmtpPort
            ,
        LogPath
            ,
        RightsTableJson
            ,
        RoleTableJson
            ,
        ModuleTableJson
            ,
        UserTableJson
            ,
        GROUPSJson
            ,
        BulkUploadPath
            ,
        ImagePath
            ,
        FeatureColumn
            ,
        RoleColumn
          ,
        DepartmentColumn
            ,
        GroupColumn
            ,
        UserDetailsColumn
            ,
        UserColumn
            ,
        EmailSubject
            ,
        Password
            ,
        DepartmentTableJson
            ,
        MenuNames
            ,
        LMSSaltValue
            ,
        UseBetaLogin
            ,
        HospitalName
            ,
        HospitalAddress
            ,
        HospitalContact
            ,
        HospitalFax
            ,
        HospitalEmail
            ,
        HospitalIso
            ,
        MedicalName
            ,
        MedicalRegNo
            ,
        PatientUploadPath
        , TemplateUploadPath
        
    }
}
